spring.application.name=travel-ai
openai.api.key=${OPENAI_API_KEY:}
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-3.5-flash-lite

messenger.verify-token:${MESSENGER_VERIFY_TOKEN:}
messenger.page-access-token: ${MESSENGER_PAGE_ACCESS_TOKEN:}